version: "3.9"
   
services:
  db:
    build: postgres/    
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=pik_gis
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=a17dvrm17
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db